spring:
  application:
    name: timchen-live-im-core-server
  cloud:
    nacos:
      discovery:
        ip: 172.23.48.1:8848
  data:
    redis:
      port: 6379
      host: timchen.db
      lettuce:
        pool:
          min-idle: 10
          max-idle: 20
          max-active: 50
timchen:
  im:
    tcp:
      port: 8085
    ws:
      port: 8086

  rmq:
    producer:
      nameSrv: timchen.rmq.com:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
    qos-port: 22222
  registry:
    address: nacos://timchen.nacos.com:8848?namespace=timchen-live-test&&username=timchen&&password=cxl123456
  protocol:
    name: dubbo
    port: -1